import { FormEvent, ReactNode, useEffect, useMemo, useState } from "react";

const clinicPhoto = "https://images.unsplash.com/photo-1606811841689-23dfddce3e95?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixlib=rb-4.1.0&q=85&w=1600";
const xrayPhoto = "https://images.unsplash.com/photo-1522849696084-818b29dfe210?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixlib=rb-4.1.0&q=85&w=1200";
type Role = "Dental Professional" | "Clinic Staff" | "Administrator";
type Account = { name:string; email:string; password:string; role:Role; initials:string };
type Patient = { id:string; name:string; gender:string; dob:string; phone:string; address:string; emergency:string; notes:string; status:"Active"|"Inactive"; concern:string; date:string; owner:string };
type Audit = { id:number; user:string; action:string; record:string; time:string };
type ModalName = "patient"|"assessment"|"symptom"|"xray"|"viewer"|"reject"|"forgot"|"user"|"event"|"profile"|null;

const initialPatients: Patient[] = [
  {id:"PT-2026-0184",name:"Aline Niyonsaba",gender:"Female",dob:"1992-04-16",phone:"078 432 9801",address:"Kicukiro, Kigali",emergency:"078 111 2033",notes:"Allergy: Penicillin",status:"Active",concern:"Persistent sensitivity",date:"2026-08-19",owner:"diane@oridental.rw"},
  {id:"PT-2026-0183",name:"Kevin Mugisha",gender:"Male",dob:"1998-11-02",phone:"072 901 3442",address:"Masaka, Kigali",emergency:"078 220 1920",notes:"No known allergies",status:"Active",concern:"Molar pain",date:"2026-08-19",owner:"diane@oridental.rw"},
  {id:"PT-2026-0181",name:"Imani Uwase",gender:"Female",dob:"1985-07-21",phone:"078 114 8020",address:"Gasabo, Kigali",emergency:"078 022 1991",notes:"Diabetic",status:"Active",concern:"Routine assessment",date:"2026-08-18",owner:"claire@oridental.rw"},
  {id:"PT-2026-0179",name:"Eric Murenzi",gender:"Male",dob:"1974-02-08",phone:"073 284 1129",address:"Nyarugenge, Kigali",emergency:"078 412 8810",notes:"Hypertension",status:"Inactive",concern:"Gum inflammation",date:"2026-08-17",owner:"patrick@oridental.rw"},
];
const demoAccounts: Account[] = [
  {name:"Dr. Diane Uwase",email:"diane@oridental.rw",password:"Demo2026!",role:"Dental Professional",initials:"DU"},
  {name:"Claire Uwera",email:"claire@oridental.rw",password:"Staff2026!",role:"Clinic Staff",initials:"CU"},
  {name:"Patrick Habineza",email:"patrick@oridental.rw",password:"Admin2026!",role:"Administrator",initials:"PH"},
];
const nav = ["Dashboard","Patients","Assessments","Symptoms","AI Symptom Analysis","Dental X-Rays","AI X-Ray Review","Decision Support","Treatment Plans","Professional Review","Clinical History","Reports","Audit & Activity","System Administration"];
const icon: Record<string,string> = {Dashboard:"▦",Patients:"P",Assessments:"A",Symptoms:"S","AI Symptom Analysis":"AI","Dental X-Rays":"XR","AI X-Ray Review":"AI","Decision Support":"D","Treatment Plans":"T","Professional Review":"R","Clinical History":"H",Reports:"RP","Audit & Activity":"AU","System Administration":"AD"};

function Logo(){return <span className="brand"><span className="brand-mark">O</span><span>ORI Dental <span>AI</span></span></span>}
function Button({children,onClick,secondary=false,type="button",className="",disabled=false}:{children:ReactNode;onClick?:()=>void;secondary?:boolean;type?:"button"|"submit";className?:string;disabled?:boolean}){return <button type={type} onClick={onClick} disabled={disabled} className={`${secondary?"btn-secondary":"btn-primary"} ${className}`}>{children}</button>}
function Badge({children}:{children:string}){const c=children.includes("Confirm")||children==="Active"?"green":children.includes("Pending")||children==="Proposed"?"amber":children.includes("AI")?"violet":"gray";return <span className={`badge ${c}`}><i/>{children}</span>}
function Modal({title,children,onClose,wide=false}:{title:string;children:ReactNode;onClose:()=>void;wide?:boolean}){
  useEffect(()=>{const k=(e:KeyboardEvent)=>e.key==="Escape"&&onClose();window.addEventListener("keydown",k);return()=>window.removeEventListener("keydown",k)},[onClose]);
  return <div className="modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><section className={`modal-card ${wide?"wide":""}`}><header><div><span className="eyebrow teal">ORI DENTAL AI</span><h2>{title}</h2></div><button onClick={onClose} aria-label="Close">×</button></header>{children}</section></div>
}
function Toast({text}:{text:string}){return <div className="toast"><b>✓</b>{text}</div>}
function Spinner({label="Processing..."}:{label?:string}){return <div className="loading-state"><i/><b>{label}</b><span>Please wait a moment</span></div>}

function Login({accounts,onLogin,onCreate,onForgot}:{accounts:Account[];onLogin:(account:Account)=>void;onCreate:(account:Account)=>void;onForgot:()=>void}){
  const [email,setEmail]=useState(""),[password,setPassword]=useState(""),[error,setError]=useState(""),[creating,setCreating]=useState(false);
  function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const data=new FormData(e.currentTarget);if(creating){const name=String(data.get("name")||"").trim(),newEmail=String(data.get("email")||"").trim().toLowerCase(),newPassword=String(data.get("password")||""),confirm=String(data.get("confirm")||""),role=String(data.get("role")) as Role;if(!name||!newEmail||newPassword.length<6){setError("Enter a name, valid email and a password of at least 6 characters.");return}if(newPassword!==confirm){setError("Passwords do not match.");return}if(accounts.some(a=>a.email===newEmail)){setError("An account with this email already exists.");return}onCreate({name,email:newEmail,password:newPassword,role,initials:name.split(" ").map(x=>x[0]).join("").slice(0,2).toUpperCase()});return}const account=accounts.find(a=>a.email===email.trim().toLowerCase()&&a.password===password);if(!account){setError("Email or password is incorrect.");return}onLogin(account)}
  return <main className="auth-shell"><section className="auth-visual" style={{backgroundImage:`linear-gradient(120deg,rgba(5,32,40,.87),rgba(5,54,63,.52)),url("${clinicPhoto}")`}}><Logo/><div className="auth-copy"><span className="eyebrow">INTELLIGENT DENTAL CARE</span><h1>Better insight.<br/>Confident care.</h1><p>One secure workspace for dental assessment, X-ray review and clinician-led treatment planning.</p><div className="trust-row"><span>✓ Clinician controlled</span><span>✓ Fully auditable</span></div></div><p className="photo-credit">Photo by Caroline LM on Unsplash</p></section>
    <section className="auth-panel"><div className="auth-card"><div className="mobile-brand"><Logo/></div><div className="auth-heading"><span className="step-label">{creating?"NEW AUTHORIZED USER":"WELCOME BACK"}</span><h2>{creating?"Create your account":"Sign in to your workspace"}</h2><p>{creating?"Your role is saved to your account and detected automatically at login.":"Enter your account details or choose a demo user below."}</p></div><form className="auth-form" onSubmit={submit}>
      {creating&&<label className="field"><span>Full name</span><div className="field-wrap"><input name="name" placeholder="Your full name"/></div></label>}
      <label className="field"><span>Email address</span><div className={`field-wrap ${error?"field-error":""}`}><input name="email" value={email} onChange={e=>setEmail(e.target.value)} type="email" placeholder="name@oridental.rw"/></div></label>
      <label className="field"><span>Password</span><div className={`field-wrap ${error?"field-error":""}`}><input name="password" value={password} onChange={e=>setPassword(e.target.value)} type="password" placeholder="Enter your password"/></div></label>
      {creating&&<><label className="field"><span>Confirm password</span><div className="field-wrap"><input name="confirm" type="password" placeholder="Repeat your password"/></div></label><label className="field"><span>Account type</span><div className="field-wrap"><select name="role"><option>Dental Professional</option><option>Clinic Staff</option><option>Administrator</option></select></div></label></>}
      {error&&<p className="form-error">{error}</p>}{!creating&&<div className="form-meta"><label><input type="checkbox" defaultChecked/>Remember me</label><button type="button" onClick={onForgot}>Forgot password?</button></div>}<Button type="submit" className="auth-submit">{creating?"Create account & continue":"Sign in automatically →"}</Button>
    </form>{!creating&&<div className="quick-login"><span>QUICK USER LOGIN</span>{accounts.map(a=><button key={a.email} onClick={()=>onLogin(a)}><i>{a.initials}</i><b>{a.name}</b><small>{a.role}</small><em>→</em></button>)}</div>}<div className="auth-switch">{creating?"Already have an account?":"Need a new account?"}<button onClick={()=>{setCreating(!creating);setError("");setEmail("");setPassword("")}}>{creating?"Sign in":"Create account"}</button></div><div className="secure-note">Your email identifies your account and permissions automatically</div></div></section></main>
}

function Toolbar({search,setSearch,status,setStatus,date,setDate,onExport}:{search:string;setSearch:(s:string)=>void;status:string;setStatus:(s:string)=>void;date:string;setDate:(s:string)=>void;onExport:()=>void}){
  return <div className="filter-bar"><div className="search-box"><span>⌕</span><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search records..."/></div><label className="toolbar-control">Date <input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><label className="toolbar-control">Status <select value={status} onChange={e=>setStatus(e.target.value)}><option>All</option><option>Active</option><option>Inactive</option><option>Pending</option><option>Confirmed</option></select></label><button className="toolbar-export" onClick={onExport}>Export CSV</button></div>
}
function PageTitle({title,text,action,onAction}:{title:string;text:string;action?:string;onAction?:()=>void}){return <div className="module-title"><div className="module-icon">{icon[title]||"O"}</div><div><h1>{title}</h1><p>{text}</p></div>{action&&<Button onClick={onAction}>＋ {action}</Button>}</div>}
function ClinicalBoundary(){return <div className="clinical-boundary"><b>Professional review required</b><span>AI outputs are decision-support only. Final clinical decisions remain with a qualified dental professional.</span></div>}

function Dashboard({go,open,patients,reviews,userName}:{go:(p:string)=>void;open:(m:ModalName)=>void;patients:Patient[];reviews:number;userName:string}){
  const stats=[["Total patients",patients.length,"Patients"],["Assessments today",14,"Assessments"],["Pending reviews",reviews,"Professional Review"],["AI analyses",27,"AI Symptom Analysis"]];
  return <div className="page-content"><div className="welcome-row"><div><span className="eyebrow teal">MONDAY, 19 AUGUST 2026</span><h1>Good morning, {userName}</h1><p>Only records assigned to your account are shown in this workspace.</p></div><Button onClick={()=>open("patient")}>＋ Register patient</Button></div><ClinicalBoundary/>
    <div className="stats-grid">{stats.map(s=><button className="stat-card clickable" onClick={()=>go(String(s[2]))} key={String(s[0])}><div><span>{s[0]}</span><strong>{s[1]}</strong><small>Open module →</small></div><span className="stat-icon">{icon[String(s[2])]}</span></button>)}</div>
    <section className="panel quick-panel"><div className="panel-head"><div><h2>Quick actions</h2><p>Continue your clinical workflow</p></div></div><div className="quick-actions"><button onClick={()=>open("patient")}>＋<b>Register patient</b><span>Create patient record</span></button><button onClick={()=>open("assessment")}>A<b>New assessment</b><span>Document complaint</span></button><button onClick={()=>open("xray")}>XR<b>Upload X-ray</b><span>Link dental image</span></button><button onClick={()=>go("Professional Review")}>R<b>Review pending</b><span>{reviews} need attention</span></button></div></section>
    <section className="panel"><div className="panel-head"><div><h2>Recent patient cases</h2><p>Click any row to open the patient profile</p></div><button onClick={()=>go("Patients")}>View all →</button></div><div className="generic-table">{patients.slice(0,4).map(p=><button className="patient-list-row" key={p.id} onClick={()=>go(`profile:${p.id}`)}><span className="avatar">{p.name.split(" ").map(x=>x[0]).join("")}</span><span><b>{p.name}</b><small>{p.id}</small></span><span>{p.concern}</span><Badge>{p.status}</Badge><span>›</span></button>)}</div></section>
  </div>
}

function Patients({patients,go,open,toast}:{patients:Patient[];go:(p:string)=>void;open:(m:ModalName)=>void;toast:(s:string)=>void}){
  const [search,setSearch]=useState(""),[status,setStatus]=useState("All"),[date,setDate]=useState("");
  const rows=useMemo(()=>patients.filter(p=>(p.name+" "+p.id+" "+p.phone).toLowerCase().includes(search.toLowerCase())&&(status==="All"||p.status===status)&&(!date||p.date===date)),[patients,search,status,date]);
  return <div className="page-content"><PageTitle title="Patients" text="Register, search, update and manage complete patient records." action="Register patient" onAction={()=>open("patient")}/><Toolbar {...{search,setSearch,status,setStatus,date,setDate}} onExport={()=>toast("Exported to CSV")}/><section className="panel data-panel"><div className="panel-head"><div><h2>Patient records</h2><p>{rows.length} records shown</p></div></div>{rows.length===0?<div className="empty">No patients match these filters.</div>:rows.map(p=><button className="generic-row patient-grid" key={p.id} onClick={()=>go(`profile:${p.id}`)}><span><b>{p.name}</b><small>{p.id}</small></span><span>{p.phone}</span><span>{p.concern}</span><span><Badge>{p.status}</Badge></span><b>›</b></button>)}</section></div>
}

function PatientProfile({patient,go,open,userName}:{patient:Patient;go:(p:string)=>void;open:(m:ModalName)=>void;userName:string}){
  const [tab,setTab]=useState("Overview");const tabs=["Overview","Assessments","X-rays","Treatment plans","History"];
  return <div className="page-content"><button className="back-link" onClick={()=>go("Patients")}>← Back to patients</button><div className="profile-hero"><span className="profile-avatar">{patient.name.split(" ").map(x=>x[0]).join("")}</span><div><Badge>{patient.status}</Badge><h1>{patient.name}</h1><p>{patient.id} · {patient.gender} · Born {patient.dob}</p></div><div className="profile-actions"><Button secondary onClick={()=>open("patient")}>Edit details</Button><Button secondary onClick={()=>open("xray")}>Upload X-ray</Button><Button onClick={()=>open("assessment")}>New assessment</Button></div></div><div className="tabs">{tabs.map(t=><button className={tab===t?"active":""} onClick={()=>setTab(t)} key={t}>{t}</button>)}</div>
    <section className="panel profile-panel">{tab==="Overview"?<div className="detail-grid"><div><small>PHONE</small><b>{patient.phone}</b></div><div><small>ADDRESS</small><b>{patient.address}</b></div><div><small>EMERGENCY CONTACT</small><b>{patient.emergency}</b></div><div><small>MEDICAL NOTES</small><b>{patient.notes}</b></div></div>:<div className="timeline"><article><i/><div><b>{tab} record</b><p>{tab==="Assessments"?"Sensitivity assessment submitted for professional review.":tab==="X-rays"?"Panoramic X-ray linked to this patient.":tab==="Treatment plans"?"Restorative plan draft available.":"Patient registered and consent recorded."}</p><small>19 August 2026 · {userName}</small></div><button onClick={()=>go(tab==="X-rays"?"AI X-Ray Review":tab==="History"?"Clinical History":"Assessments")}>Open →</button></article></div>}</section>
  </div>
}

const listRows:Record<string,string[][]>={
  Assessments:[["Aline Niyonsaba","Dental pain","Dr. Uwase","Pending"],["Kevin Mugisha","Molar assessment","Dr. Uwase","Confirmed"],["Imani Uwase","Routine exam","Dr. Nkurunziza","Confirmed"]],
  Symptoms:[["Aline Niyonsaba","Sensitivity · tooth 26","Severity 6/10","Active"],["Kevin Mugisha","Pain · tooth 36","Severity 8/10","Active"]],
};
function ListModule({name,go,open,toast,patients}:{name:string;go:(p:string)=>void;open:(m:ModalName)=>void;toast:(s:string)=>void;patients:Patient[]}){
  const [search,setSearch]=useState(""),[status,setStatus]=useState("All"),[date,setDate]=useState("");const allowed=new Set(patients.map(p=>p.name));const rows=(listRows[name]||[]).filter(r=>allowed.has(r[0])&&r.join(" ").toLowerCase().includes(search.toLowerCase())&&(status==="All"||r.includes(status)));
  return <div className="page-content"><PageTitle title={name} text={name==="Assessments"?"Capture complaints, observations and professional clinical notes.":"Record structured patient-reported and clinically observed symptoms."} action={name==="Assessments"?"New assessment":"Add symptom"} onAction={()=>open(name==="Assessments"?"assessment":"symptom")}/><Toolbar {...{search,setSearch,status,setStatus,date,setDate}} onExport={()=>toast("Exported to CSV")}/><section className="panel data-panel"><div className="panel-head"><div><h2>Recent {name.toLowerCase()}</h2><p>{rows.length} records shown</p></div>{name==="Symptoms"&&<Button onClick={()=>go("AI Symptom Analysis")}>Run AI analysis</Button>}</div>{rows.length?rows.map((r,i)=><button className="generic-row" key={i} onClick={()=>name==="Symptoms"?go("AI Symptom Analysis"):open("assessment")}>{r.map((x,j)=><span key={x}>{j===0?<b>{x}</b>:j===3?<Badge>{x}</Badge>:x}</span>)}<b>›</b></button>):<div className="empty">No records found.</div>}</section></div>
}

function AISymptoms({go,audit,patientName}:{go:(p:string)=>void;audit:(a:string,r:string)=>void;patientName:string}){
  const [loading,setLoading]=useState(false),[done,setDone]=useState(false);function run(){setLoading(true);setDone(false);setTimeout(()=>{setLoading(false);setDone(true);audit("Ran AI symptom analysis",patientName)},2000)}
  return <div className="page-content"><PageTitle title="AI Symptom Analysis" text="Analyze structured symptoms and present transparent decision-support findings." action={done?"Re-run analysis":"Run analysis"} onAction={run}/><ClinicalBoundary/>{loading?<section className="panel"><Spinner label="Analyzing symptom patterns..."/></section>:done?<section className="ai-result-grid"><article className="panel result-card"><span className="eyebrow teal">AI SUGGESTION — REQUIRES DENTIST CONFIRMATION</span><h2>Likely clinical patterns</h2><div className="result-line"><div><b>Dentinal hypersensitivity</b><span>Cold-triggered pain · tooth 26</span></div><strong>86%</strong></div><div className="result-line"><div><b>Possible dental caries</b><span>Persistent localized sensitivity</span></div><strong>72%</strong></div><div className="result-buttons"><Button secondary onClick={run}>Re-run</Button><Button onClick={()=>go("Decision Support")}>Send to Decision Support →</Button></div></article><article className="panel result-card"><h2>Analysis details</h2><p>Model: ORI Symptom Support 2.4</p><p>Inputs: pain, sensitivity, duration and tooth region</p><Button secondary onClick={()=>alert("Detailed feature contribution view opened.")}>View details</Button></article></section>:<section className="panel empty-state"><b>No analysis has been run</b><p>Select the active patient symptoms and run an analysis.</p><Button onClick={run}>Run analysis</Button></section>}</div>
}

function DentalXrays({go,open,toast,patientName}:{go:(p:string)=>void;open:(m:ModalName)=>void;toast:(s:string)=>void;patientName:string}){
  const [deleted,setDeleted]=useState(false);return <div className="page-content"><PageTitle title="Dental X-Rays" text="Upload, link, view and manage diagnostic dental images." action="Upload X-ray" onAction={()=>open("xray")}/><div className="xray-grid">{patientName!=="No patient selected"&&!deleted&&<article className="panel xray-thumb"><img src={xrayPhoto} alt="Panoramic dental X-ray"/><div><b>{patientName} · Panoramic</b><small>19 Aug 2026 · Full mouth</small><span><Button secondary onClick={()=>open("viewer")}>View</Button><Button secondary onClick={()=>toast(`X-ray linked to ${patientName}`)}>Link patient</Button><button className="danger-link" onClick={()=>confirm("Delete this X-ray?")&&setDeleted(true)}>Delete</button></span></div></article>}<button className="upload-tile" onClick={()=>open("xray")}>＋<b>Drag & drop X-ray</b><span>or browse image files</span></button></div><div className="next-action"><Button onClick={()=>go("AI X-Ray Review")}>Open AI X-Ray Review →</Button></div></div>
}
function AIXray({go,audit,patientName}:{go:(p:string)=>void;audit:(a:string,r:string)=>void;patientName:string}){
  const [loading,setLoading]=useState(false),[done,setDone]=useState(false),[overlay,setOverlay]=useState(true),[zoom,setZoom]=useState(1),[finding,setFinding]=useState("Pending");
  function analyze(){setLoading(true);setTimeout(()=>{setLoading(false);setDone(true);audit("Completed AI X-ray review",patientName)},2000)}
  return <div className="page-content"><PageTitle title="AI X-Ray Review" text="Inspect AI overlays and make a professional finding decision." action={done?"Re-analyze X-ray":"Analyze X-ray"} onAction={analyze}/><ClinicalBoundary/>{loading?<section className="panel"><Spinner label="Reviewing dental X-ray..."/></section>:<div className="module-layout"><section className="panel xray-viewer"><div className="viewer-tools"><button onClick={()=>setZoom(Math.max(.7,zoom-.1))}>−</button><button onClick={()=>setZoom(Math.min(1.5,zoom+.1))}>＋</button><button onClick={()=>setOverlay(!overlay)}>{overlay?"Hide":"Show"} AI overlay</button></div><div className="xray-image"><img style={{transform:`scale(${zoom})`}} src={xrayPhoto} alt="Dental X-ray under review"/>{done&&overlay&&<><span className="overlay-box box-one">Possible caries · 82%</span><span className="overlay-box box-two">Periapical change · 71%</span></>}</div></section><aside className="panel findings"><div className="panel-head"><div><h2>AI findings</h2><p>ORI Dental Vision 2.4</p></div>{done&&<Badge>{finding}</Badge>}</div>{done?<><div className="finding-item"><b>Possible caries — tooth 36</b><p>Interproximal radiolucency detected with 82% confidence.</p><div><Button secondary onClick={()=>setFinding("Accepted")}>Accept</Button><Button secondary onClick={()=>setFinding("Flagged")}>Flag</Button></div></div><div className="finding-item"><b>Periapical change — tooth 26</b><p>Subtle region detected with 71% confidence.</p></div><Button className="full" onClick={()=>go("Decision Support")}>Send to Decision Support →</Button></>:<div className="empty">Run analysis to display overlays and findings.</div>}</aside></div>}</div>
}

function DecisionSupport({go}:{go:(p:string)=>void}){return <div className="page-content"><PageTitle title="Decision Support" text="Review combined symptom and X-ray findings before creating a plan."/><ClinicalBoundary/><div className="support-grid"><article className="panel result-card"><span className="eyebrow teal">SYMPTOM RESULT</span><h2>Dentinal hypersensitivity</h2><strong className="big-confidence">86%</strong><p>Cold-triggered pain localized around tooth 26.</p><Button secondary onClick={()=>go("AI Symptom Analysis")}>View symptom result</Button></article><article className="panel result-card"><span className="eyebrow teal">X-RAY RESULT</span><h2>Possible interproximal caries</h2><strong className="big-confidence">82%</strong><p>Radiolucency detected near tooth 36.</p><Button secondary onClick={()=>go("AI X-Ray Review")}>View X-ray result</Button></article></div><section className="panel decision-summary"><h2>Combined clinical finding</h2><p>Findings may support a focused clinical examination of teeth 26 and 36. Professional confirmation is required before treatment.</p><Button onClick={()=>go("Treatment Plans")}>Create treatment plan →</Button></section></div>}

function TreatmentPlans({go,audit,toast,pending,setPending,patientName}:{go:(p:string)=>void;audit:(a:string,r:string)=>void;toast:(s:string)=>void;pending:number;setPending:(n:number)=>void;patientName:string}){
  const [steps,setSteps]=useState(["Clinical examination and vitality test","Bitewing radiograph confirmation","Composite restoration — tooth 36"]);function submit(){setPending(pending+1);audit("Submitted treatment plan for review",patientName);toast("Plan submitted for professional review");go("Professional Review")}
  return <div className="page-content"><PageTitle title="Treatment Plans" text="Build an ordered plan from professionally reviewed findings." action="New plan" onAction={()=>setSteps(["New clinical procedure"])}/><section className="panel plan-editor"><div className="panel-head"><div><h2>{patientName} · Proposed plan</h2><p>Estimated visits: 2</p></div><Badge>Proposed</Badge></div>{steps.map((s,i)=><div className="plan-step" key={`${s}-${i}`}><i>{i+1}</i><input value={s} onChange={e=>setSteps(steps.map((x,j)=>j===i?e.target.value:x))}/><button disabled={i===0} onClick={()=>{const a=[...steps];[a[i-1],a[i]]=[a[i],a[i-1]];setSteps(a)}}>↑</button><button onClick={()=>setSteps(steps.filter((_,j)=>j!==i))}>×</button></div>)}<button className="add-procedure" onClick={()=>setSteps([...steps,"New procedure"])}>＋ Add procedure</button><label className="notes-block">Professional notes<textarea placeholder="Add clinical rationale and patient considerations..."/></label><div className="form-actions"><Button secondary onClick={()=>toast("Treatment plan saved as draft")}>Save draft</Button><Button onClick={submit}>Submit for review →</Button></div></section></div>
}

function ProfessionalReview({pending,setPending,go,audit,open,toast,patientName,userName}:{pending:number;setPending:(n:number)=>void;go:(p:string)=>void;audit:(a:string,r:string)=>void;open:(m:ModalName)=>void;toast:(s:string)=>void;patientName:string;userName:string}){
  const [note,setNote]=useState("");function confirmReview(){setPending(Math.max(0,pending-1));audit("Confirmed final clinical decision",patientName);toast(`Confirmed by ${userName} · saved to History and Audit`)}
  return <div className="page-content"><PageTitle title="Professional Review" text="Confirm, edit or reject AI-supported findings and treatment plans."/><ClinicalBoundary/><section className="panel review-detail"><div className="panel-head"><div><h2>{patientName} · Treatment plan review</h2><p>Submitted today at 10:42</p></div><Badge>{pending?"Pending review":`Confirmed by ${userName}`}</Badge></div><div className="review-body"><div><b>Proposed clinical decision</b><p>Focused examination followed by composite restoration if caries is clinically confirmed.</p></div><label>Professional note<textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="Document your clinical reasoning..."/></label></div><div className="review-actions"><Button secondary onClick={()=>toast("Review opened for editing")}>Edit</Button><Button secondary onClick={()=>open("reject")}>Reject</Button><Button onClick={confirmReview} disabled={!pending}>Confirm final decision</Button></div></section><Button secondary onClick={()=>go("Clinical History")}>Open Clinical History</Button></div>
}

function History({patients,go,userName}:{patients:Patient[];go:(p:string)=>void;userName:string}){const [patient,setPatient]=useState(patients[0]?.name||"No patient selected");return <div className="page-content"><PageTitle title="Clinical History" text="Chronological assessments, X-rays, AI findings, plans and final decisions."/><div className="history-toolbar"><label>Patient <select value={patient} onChange={e=>setPatient(e.target.value)}>{patients.map(p=><option key={p.id}>{p.name}</option>)}</select></label><Button secondary onClick={()=>window.print()}>Print history</Button><Button secondary onClick={()=>go("AI X-Ray Review")}>Compare X-rays</Button></div>{patients.length?<section className="panel timeline">{[["Final clinical decision confirmed",`Confirmed by ${userName}`,"19 Aug · 11:03"],["Treatment plan submitted","Composite restoration plan","19 Aug · 10:42"],["AI X-ray review completed","Possible caries · 82%","19 Aug · 10:31"],["Symptom analysis completed","Hypersensitivity · 86%","19 Aug · 10:12"],["Assessment created","Dental assessment","19 Aug · 09:48"]].map(x=><article key={x[0]}><i/><div><b>{x[0]}</b><p>{x[1]}</p><small>{x[2]} · {patient}</small></div><button onClick={()=>alert(`${x[0]}\n${x[1]}`)}>Open →</button></article>)}</section>:<div className="panel empty">No clinical history is assigned to this account.</div>}</div>}

function Reports({toast}:{toast:(s:string)=>void}){const [type,setType]=useState("Clinical summary"),[ready,setReady]=useState(false);return <div className="page-content"><PageTitle title="Reports" text="Generate assessment, treatment, AI analysis and clinical reports."/><section className="panel report-builder"><div className="report-controls"><label>Report type<select value={type} onChange={e=>setType(e.target.value)}><option>Clinical summary</option><option>Assessment report</option><option>AI analysis outcomes</option><option>Treatment plans</option></select></label><label>Date from<input type="date" defaultValue="2026-08-01"/></label><label>Date to<input type="date" defaultValue="2026-08-19"/></label><Button onClick={()=>{setReady(true);toast("Report ready")}}>Generate report</Button></div>{ready?<div className="report-preview"><span>ORI DENTAL CLINIC · KIGALI</span><h2>{type}</h2><p>19 August 2026</p><div className="preview-lines"/><div className="preview-lines short"/><Button onClick={()=>toast("Report PDF downloaded")}>Download PDF</Button></div>:<div className="empty">Choose report settings and select Generate to open a preview.</div>}</section></div>}

function AuditPage({events,open,setEvent,toast}:{events:Audit[];open:(m:ModalName)=>void;setEvent:(e:Audit)=>void;toast:(s:string)=>void}){const [q,setQ]=useState("");const rows=events.filter(e=>e.user.toLowerCase().includes(q.toLowerCase())||e.action.toLowerCase().includes(q.toLowerCase()));return <div className="page-content"><PageTitle title="Audit & Activity" text="Trace every patient, AI, review and system action."/><div className="filter-bar"><div className="search-box"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Filter by user or action"/></div><input className="toolbar-control" type="date"/><button className="toolbar-export" onClick={()=>toast("Audit log exported to CSV")}>Export log</button></div><section className="panel">{rows.map(e=><button className="audit-row" key={e.id} onClick={()=>{setEvent(e);open("event")}}><span><b>{e.action}</b><small>{e.record}</small></span><span>{e.user}</span><span>{e.time}</span><b>›</b></button>)}</section></div>}

function Admin({toast,open}:{toast:(s:string)=>void;open:(m:ModalName)=>void}){const [tab,setTab]=useState("Users & roles");return <div className="page-content"><PageTitle title="System Administration" text="Manage access, clinic configuration and AI model settings."/><div className="tabs">{["Users & roles","Clinic settings","AI model settings"].map(t=><button className={tab===t?"active":""} onClick={()=>setTab(t)} key={t}>{t}</button>)}</div><section className="panel admin-panel">{tab==="Users & roles"?<><div className="panel-head"><div><h2>Authorized users</h2><p>Role and account management</p></div><Button onClick={()=>open("user")}>＋ Add user</Button></div>{[["Dr. Diane Uwase","Dental Professional","Active"],["Claire Uwera","Clinic Staff","Active"],["Patrick Habineza","Administrator","Active"]].map(u=><div className="user-row" key={u[0]}><span><b>{u[0]}</b><small>{u[1]}</small></span><Badge>{u[2]}</Badge><button onClick={()=>toast(`Role editor opened for ${u[0]}`)}>Edit role</button><button onClick={()=>toast(`${u[0]} deactivated`)}>Deactivate</button><button onClick={()=>toast("Password reset link sent")}>Reset password</button></div>)}</>:<div className="settings-form"><label>{tab==="Clinic settings"?"Clinic name":"Active model"}<input defaultValue={tab==="Clinic settings"?"ORI Dental Clinic":"ORI Dental Vision 2.4"}/></label><label>{tab==="Clinic settings"?"Location":"Confidence threshold"}<input defaultValue={tab==="Clinic settings"?"Kicukiro, Masaka, Kigali":"70%"}/></label><label>{tab==="Clinic settings"?"Contact email":"Human review"}<input defaultValue={tab==="Clinic settings"?"info@oridental.rw":"Required for every AI result"}/></label><Button onClick={()=>toast("Settings saved")}>Save settings</Button></div>}</section></div>}

function AppShell({account,onLogout}:{account:Account;onLogout:()=>void}){
  const role=account.role;
  const [page,setPage]=useState("Dashboard"),[patients,setPatients]=useState(initialPatients),[modal,setModal]=useState<ModalName>(null),[toast,setToast]=useState(""),[pending,setPending]=useState(3),[mobile,setMobile]=useState(false),[profileMenu,setProfileMenu]=useState(false),[clinic,setClinic]=useState(false),[notices,setNotices]=useState(false),[globalSearch,setGlobalSearch]=useState(false),[event,setEvent]=useState<Audit|null>(null);
  const [events,setEvents]=useState<Audit[]>([{id:1,user:account.name,action:"Signed in",record:`${account.role} workspace`,time:"Just now"}]);
  const ownPatients=patients.filter(p=>p.owner===account.email);const selectedId=page.startsWith("profile:")?page.split(":")[1]:null;const selected=ownPatients.find(p=>p.id===selectedId)||ownPatients[0]||{id:"",name:"No patient selected",gender:"",dob:"",phone:"",address:"",emergency:"",notes:"",status:"Active",concern:"",date:"2026-08-19",owner:account.email};
  function go(p:string){setPage(p);setMobile(false);setGlobalSearch(false)}
  function notify(s:string){setToast(s);setTimeout(()=>setToast(""),2600)}
  function audit(action:string,record:string){setEvents(e=>[{id:Date.now(),user:account.name,action,record,time:"Just now"},...e])}
  useEffect(()=>{const key=(e:KeyboardEvent)=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==="k"){e.preventDefault();setGlobalSearch(true)}};window.addEventListener("keydown",key);return()=>window.removeEventListener("keydown",key)},[]);
  function savePatient(fd:FormData){const name=String(fd.get("name")||"").trim(),phone=String(fd.get("phone")||"").trim(),dob=String(fd.get("dob")||""),address=String(fd.get("address")||"").trim(),emergency=String(fd.get("emergency")||"").trim();if(!name||!phone||!dob||!address||!emergency)return false;const isEdit=modal==="patient"&&page.startsWith("profile:");if(isEdit&&selected){setPatients(ps=>ps.map(p=>p.id===selected.id?{...p,name,phone,address,emergency,notes:String(fd.get("notes")),gender:String(fd.get("gender")),dob}:p));audit("Updated patient details",name);notify("Patient details updated")}else{const p:Patient={id:`PT-2026-${String(185+patients.length).padStart(4,"0")}`,name,phone,gender:String(fd.get("gender")),dob,address,emergency,notes:String(fd.get("notes")),status:"Active",concern:"New patient",date:"2026-08-19",owner:account.email};setPatients(ps=>[p,...ps]);audit("Registered patient",name);notify("Patient registered");go(`profile:${p.id}`)}setModal(null);return true}
  const visibleNav=nav.filter(n=>!(role==="Clinic Staff"&&n==="System Administration"));
  let content:ReactNode;if(page==="Dashboard")content=<Dashboard go={go} open={setModal} patients={ownPatients} reviews={pending} userName={account.name}/>;else if(page==="Patients")content=<Patients patients={ownPatients} go={go} open={setModal} toast={notify}/>;else if(page.startsWith("profile:")&&selected.id)content=<PatientProfile patient={selected} go={go} open={setModal} userName={account.name}/>;else if(page==="Assessments"||page==="Symptoms")content=<ListModule name={page} go={go} open={setModal} toast={notify} patients={ownPatients}/>;else if(page==="AI Symptom Analysis")content=<AISymptoms go={go} audit={audit} patientName={selected.name}/>;else if(page==="Dental X-Rays")content=<DentalXrays go={go} open={setModal} toast={notify} patientName={selected.name}/>;else if(page==="AI X-Ray Review")content=<AIXray go={go} audit={audit} patientName={selected.name}/>;else if(page==="Decision Support")content=<DecisionSupport go={go}/>;else if(page==="Treatment Plans")content=<TreatmentPlans go={go} audit={audit} toast={notify} pending={pending} setPending={setPending} patientName={selected.name}/>;else if(page==="Professional Review")content=<ProfessionalReview pending={pending} setPending={setPending} go={go} audit={audit} open={setModal} toast={notify} patientName={selected.name} userName={account.name}/>;else if(page==="Clinical History")content=<History patients={ownPatients} go={go} userName={account.name}/>;else if(page==="Reports")content=<Reports toast={notify}/>;else if(page==="Audit & Activity")content=<AuditPage events={events.filter(e=>e.user===account.name)} open={setModal} setEvent={setEvent} toast={notify}/>;else content=<Admin toast={notify} open={setModal}/>;
  return <div className="app-shell"><aside className={`sidebar ${mobile?"open":""}`}><button className="logo-button" onClick={()=>go("Dashboard")}><Logo/></button><button className="clinic-label" onClick={()=>setClinic(!clinic)}><span>ORI</span><div><b>ORI Dental Clinic</b><small>Kigali, Rwanda</small></div></button>{clinic&&<div className="sidebar-pop"><b>ORI Dental Clinic</b><span>Kicukiro, Masaka, Kigali</span><small>Partner clinical facility</small></div>}<nav>{visibleNav.map(n=><button className={(page===n||(n==="Patients"&&page.startsWith("profile:")))?"active":""} onClick={()=>go(n)} key={n}><i className="nav-glyph">{icon[n]}</i><span>{n}</span>{n==="Professional Review"&&<em>{pending}</em>}</button>)}</nav><button className="sidebar-user" onClick={()=>setProfileMenu(!profileMenu)}><span>{account.initials}</span><div><b>{account.name}</b><small>{role}</small></div><b>›</b></button>{profileMenu&&<ProfileMenu account={account} onAction={x=>{setProfileMenu(false);if(x==="logout"||x==="role")onLogout();else setModal("profile")}}/>}</aside>
      <div className="main-area"><header className="topbar"><button className="menu-button" onClick={()=>setMobile(!mobile)}>☰</button><div className="product-title"><b>AI-Powered Dental Diagnosis & Treatment Planning Platform</b><span>Intelligent assessment and professional decision support</span></div><div className="top-actions"><button className="global-search" onClick={()=>setGlobalSearch(true)}>⌕ <span>Search your patients and cases...</span><kbd>⌘ K</kbd></button><button className="notification" onClick={()=>setNotices(!notices)}>◌<i/></button><button className="header-user" onClick={()=>setProfileMenu(!profileMenu)}><span>{account.initials}</span><div><b>{account.name}</b><small>{role}</small></div></button></div>{notices&&<div className="top-pop notifications"><b>Your notifications</b><button onClick={()=>go("Professional Review")}>You have {pending} pending reviews<small>Open your review queue</small></button><button onClick={()=>go("Patients")}>{ownPatients.length} patient records assigned to you<small>View your patients</small></button></div>}{profileMenu&&<div className="top-profile"><ProfileMenu account={account} onAction={x=>{setProfileMenu(false);if(x==="logout"||x==="role")onLogout();else setModal("profile")}}/></div>}</header><main>{content}</main></div>
    {globalSearch&&<GlobalSearch patients={ownPatients} go={go} close={()=>setGlobalSearch(false)}/>}
    {modal&&<ModalHost modal={modal} close={()=>setModal(null)} patient={selected} patients={ownPatients} account={account} editingPatient={page.startsWith("profile:")} savePatient={savePatient} go={go} notify={notify} audit={audit} event={event}/>}
    {toast&&<Toast text={toast}/>}</div>
}

function ProfileMenu({account,onAction}:{account:Account;onAction:(x:string)=>void}){return <div className="profile-menu"><b>{account.name}</b><small>{account.role} · {account.email}</small><button onClick={()=>onAction("profile")}>My profile</button><button onClick={()=>onAction("role")}>Switch user</button><button className="danger-link" onClick={()=>onAction("logout")}>Log out</button></div>}
function GlobalSearch({patients,go,close}:{patients:Patient[];go:(p:string)=>void;close:()=>void}){const [q,setQ]=useState("");const rows=patients.filter(p=>(p.name+p.id+p.concern).toLowerCase().includes(q.toLowerCase()));return <Modal title="Search patients and cases" onClose={close}><div className="command-search"><input autoFocus value={q} onChange={e=>setQ(e.target.value)} placeholder="Type a patient, ID or case..."/>{rows.map(p=><button key={p.id} onClick={()=>go(`profile:${p.id}`)}><span><b>{p.name}</b><small>{p.id} · {p.concern}</small></span><b>Open →</b></button>)}</div></Modal>}

function ModalHost({modal,close,patient,patients,account,editingPatient,savePatient,go,notify,audit,event}:{modal:Exclude<ModalName,null>;close:()=>void;patient:Patient;patients:Patient[];account:Account;editingPatient:boolean;savePatient:(f:FormData)=>boolean;go:(p:string)=>void;notify:(s:string)=>void;audit:(a:string,r:string)=>void;event:Audit|null}){
  const [error,setError]=useState("");function basicSave(e:FormEvent<HTMLFormElement>,message:string,next?:string){e.preventDefault();setTimeout(()=>{audit(message,patient.name);notify(message);close();if(next)go(next)},500)}
  if(modal==="patient")return <Modal title={editingPatient?"Edit patient details":"Register patient"} onClose={close} wide><form className="modal-form" onSubmit={e=>{e.preventDefault();if(!savePatient(new FormData(e.currentTarget)))setError("Full name, date of birth, phone, address and emergency contact are required.")}}><div className="form-grid"><label>Full name<input name="name" defaultValue={editingPatient?patient.name:""}/></label><label>Gender<select name="gender" defaultValue={editingPatient?patient.gender:"Female"}><option>Female</option><option>Male</option><option>Other</option></select></label><label>Date of birth<input name="dob" type="date" defaultValue={editingPatient?patient.dob:""}/></label><label>Phone<input name="phone" defaultValue={editingPatient?patient.phone:""}/></label><label>Address<input name="address" defaultValue={editingPatient?patient.address:""}/></label><label>Emergency contact<input name="emergency" defaultValue={editingPatient?patient.emergency:""}/></label></div><label>Allergies and medical notes<textarea name="notes" defaultValue={editingPatient?patient.notes:""}/></label>{error&&<p className="form-error">{error}</p>}<div className="form-actions"><Button secondary onClick={close}>Cancel</Button><Button type="submit">Save patient</Button></div></form></Modal>;
  if(modal==="assessment")return <Modal title="New dental assessment" onClose={close} wide><form className="modal-form" onSubmit={e=>basicSave(e,"Assessment saved as draft")}><div className="form-grid"><label>Patient<select defaultValue={patient.name}>{patients.map(p=><option key={p.id}>{p.name}</option>)}</select></label><label>Assessment type<select><option>Dental pain</option><option>Routine examination</option><option>Emergency</option></select></label></div><label>Chief complaint<input required placeholder="Describe the main concern"/></label><label>Clinical observations<textarea required placeholder="Document clinical observations..."/></label><label>Professional notes<textarea placeholder="Additional context..."/></label><label>Attach document<input type="file"/></label><div className="form-actions"><Button secondary onClick={close}>Cancel</Button><Button secondary type="submit">Save draft</Button><Button onClick={()=>{audit("Created assessment",patient.name);close();go("Symptoms")}}>Continue to symptoms →</Button></div></form></Modal>;
  if(modal==="symptom")return <Modal title="Add structured symptom" onClose={close}><form className="modal-form" onSubmit={e=>basicSave(e,"Symptom saved","AI Symptom Analysis")}><label>Patient<select>{patients.map(p=><option key={p.id}>{p.name}</option>)}</select></label><fieldset><legend>Category</legend><div className="chip-row">{["Pain","Swelling","Bleeding","Sensitivity","Other"].map(x=><label key={x}><input type="radio" name="cat" value={x}/><span>{x}</span></label>)}</div></fieldset><div className="form-grid"><label>Tooth number<input required placeholder="e.g. 26"/></label><label>Duration<input placeholder="e.g. 3 days"/></label></div><label>Severity: 1–10<input type="range" min="1" max="10" defaultValue="6"/></label><label>Notes<textarea/></label><div className="form-actions"><Button secondary onClick={close}>Cancel</Button><Button type="submit">Save & run AI analysis</Button></div></form></Modal>;
  if(modal==="xray")return <Modal title="Upload dental X-ray" onClose={close}><form className="modal-form" onSubmit={e=>basicSave(e,"X-ray uploaded and linked","Dental X-Rays")}><label className="drop-zone">Drop X-ray here<input type="file" accept="image/*"/><span>or select an image file</span></label><label>Link to patient<select>{patients.map(p=><option key={p.id}>{p.name}</option>)}</select></label><label>Image type<select><option>Panoramic</option><option>Bitewing</option><option>Periapical</option></select></label><div className="form-actions"><Button secondary onClick={close}>Cancel</Button><Button type="submit">Upload X-ray</Button></div></form></Modal>;
  if(modal==="viewer")return <Modal title="Panoramic X-ray viewer" onClose={close} wide><img className="modal-xray" src={xrayPhoto} alt="Panoramic dental X-ray"/><div className="form-actions"><Button secondary onClick={close}>Close</Button><Button onClick={()=>{close();go("AI X-Ray Review")}}>Review with AI →</Button></div></Modal>;
  if(modal==="reject")return <Modal title="Reject clinical recommendation" onClose={close}><form className="modal-form" onSubmit={e=>basicSave(e,"Recommendation rejected")}><label>Reason for rejection<textarea required placeholder="A reason is required for the audit record."/></label><div className="form-actions"><Button secondary onClick={close}>Cancel</Button><Button type="submit">Reject recommendation</Button></div></form></Modal>;
  if(modal==="forgot")return <Modal title="Reset password" onClose={close}><form className="modal-form" onSubmit={e=>{e.preventDefault();notify("Password reset link sent");close()}}><label>Email address<input required type="email" placeholder="professional@clinic.com"/></label><div className="form-actions"><Button secondary onClick={close}>Cancel</Button><Button type="submit">Send reset link</Button></div></form></Modal>;
  if(modal==="event"&&event)return <Modal title="Audit event details" onClose={close}><div className="detail-grid"><div><small>WHO</small><b>{event.user}</b></div><div><small>WHAT</small><b>{event.action}</b></div><div><small>RECORD</small><b>{event.record}</b></div><div><small>WHEN</small><b>{event.time}</b></div></div><div className="form-actions"><Button onClick={close}>Close</Button></div></Modal>;
  if(modal==="user")return <Modal title="Add authorized user" onClose={close}><form className="modal-form" onSubmit={e=>basicSave(e,"User saved")}><label>Full name<input required placeholder="Staff member name"/></label><label>Email address<input required type="email" placeholder="name@oridental.rw"/></label><label>Role<select><option>Dental Professional</option><option>Clinic Staff</option><option>Administrator</option></select></label><div className="form-actions"><Button secondary onClick={close}>Cancel</Button><Button type="submit">Save user</Button></div></form></Modal>;
  return <Modal title="My profile" onClose={close}><div className="detail-grid"><div><small>NAME</small><b>{account.name}</b></div><div><small>ROLE</small><b>{account.role}</b></div><div><small>EMAIL</small><b>{account.email}</b></div><div><small>CLINIC</small><b>ORI Dental Clinic</b></div></div><div className="form-actions"><Button onClick={close}>Close</Button></div></Modal>;
}

export default function Prototype(){const [accounts,setAccounts]=useState(demoAccounts),[account,setAccount]=useState<Account|null>(null),[forgot,setForgot]=useState(false);function createAccount(newAccount:Account){setAccounts(a=>[...a,newAccount]);setAccount(newAccount)}return account?<AppShell account={account} onLogout={()=>setAccount(null)}/>:<><Login accounts={accounts} onLogin={setAccount} onCreate={createAccount} onForgot={()=>setForgot(true)}/>{forgot&&<Modal title="Reset password" onClose={()=>setForgot(false)}><form className="modal-form" onSubmit={e=>{e.preventDefault();setForgot(false)}}><label>Email address<input required type="email"/></label><div className="form-actions"><Button secondary onClick={()=>setForgot(false)}>Cancel</Button><Button type="submit">Send reset link</Button></div></form></Modal>}</>}
